/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beecrypt_provider_HMACSHA512 */

#ifndef _Included_beecrypt_provider_HMACSHA512
#define _Included_beecrypt_provider_HMACSHA512
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beecrypt_provider_HMACSHA512
 * Method:    allocParam
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_beecrypt_provider_HMACSHA512_allocParam
  (JNIEnv *, jclass);

/*
 * Class:     beecrypt_provider_HMACSHA512
 * Method:    cloneParam
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_beecrypt_provider_HMACSHA512_cloneParam
  (JNIEnv *, jclass, jlong);

/*
 * Class:     beecrypt_provider_HMACSHA512
 * Method:    freeParam
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_beecrypt_provider_HMACSHA512_freeParam
  (JNIEnv *, jclass, jlong);

/*
 * Class:     beecrypt_provider_HMACSHA512
 * Method:    doFinal
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_beecrypt_provider_HMACSHA512_doFinal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     beecrypt_provider_HMACSHA512
 * Method:    init
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_beecrypt_provider_HMACSHA512_init
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     beecrypt_provider_HMACSHA512
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_beecrypt_provider_HMACSHA512_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     beecrypt_provider_HMACSHA512
 * Method:    update
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_beecrypt_provider_HMACSHA512_update__JB
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     beecrypt_provider_HMACSHA512
 * Method:    update
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_beecrypt_provider_HMACSHA512_update__J_3BII
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
