/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beecrypt_provider_DHKeyPairGenerator */

#ifndef _Included_beecrypt_provider_DHKeyPairGenerator
#define _Included_beecrypt_provider_DHKeyPairGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beecrypt_provider_DHKeyPairGenerator
 * Method:    generate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_beecrypt_provider_DHKeyPairGenerator_generate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
