/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beecrypt_provider_HMACSHA384 */

#ifndef _Included_beecrypt_provider_HMACSHA384
#define _Included_beecrypt_provider_HMACSHA384
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beecrypt_provider_HMACSHA384
 * Method:    allocParam
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_beecrypt_provider_HMACSHA384_allocParam
  (JNIEnv *, jclass);

/*
 * Class:     beecrypt_provider_HMACSHA384
 * Method:    cloneParam
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_beecrypt_provider_HMACSHA384_cloneParam
  (JNIEnv *, jclass, jlong);

/*
 * Class:     beecrypt_provider_HMACSHA384
 * Method:    freeParam
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_beecrypt_provider_HMACSHA384_freeParam
  (JNIEnv *, jclass, jlong);

/*
 * Class:     beecrypt_provider_HMACSHA384
 * Method:    doFinal
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_beecrypt_provider_HMACSHA384_doFinal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     beecrypt_provider_HMACSHA384
 * Method:    init
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_beecrypt_provider_HMACSHA384_init
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     beecrypt_provider_HMACSHA384
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_beecrypt_provider_HMACSHA384_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     beecrypt_provider_HMACSHA384
 * Method:    update
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_beecrypt_provider_HMACSHA384_update__JB
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     beecrypt_provider_HMACSHA384
 * Method:    update
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_beecrypt_provider_HMACSHA384_update__J_3BII
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
